<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * Class BlockMethodRoute
 *
 * This middleware is responsible for blocking direct GET access to specific routes
 * that should only be accessed via other means (e.g., AJAX requests from a view).
 *
 * @package App\Http\Middleware
 */
class BlockMethodRoute
{
    /**
     * Handle an incoming request.
     *
     * This method checks if the incoming request is a GET request targeting specific
     * 'penjualan' routes (like the main index, export, or report pages) and aborts
     * with a 404 error if it is. This prevents users from directly accessing URLs
     * that are intended to be loaded or triggered by other parts of the application.
     *
     * @param  Request $request The incoming HTTP request.
     * @param  Closure $next The next middleware in the pipeline.
     * @return Response The response generated by the next middleware, or an aborted response.
     */
    public function handle(Request $request, Closure $next): Response
    {
        // if ($request->isMethod('POST') && $request->path() === 'penjualan/export/excel') {
        //     // Redirect, abort, or return a specific response
        //     return $next($request);
        // }

        // abort(404);

        // blocking semua route
        // if ($request->isMethod('GET')) {
        //     abort(404);
        // }

        // return $next($request);

        if (
            $request->isMethod('GET') &&
            preg_match('#^penjualan($|/export/[^/]+$|/report$)#', $request->path())
        ) {
            abort(404, 'Tidak bisa akses halaman!');
        }

        // if (
        //     $request->isMethod('GET') &&
        //     (
        //         preg_match('#^penjualan$#', $request->path()) || // /penjualan persis
        //         preg_match('#^penjualan/export/[^/]+$#', $request->path()) // /penjualan/export/{mode}
        //     )
        // ) {
        //     abort(404);
        // }

        return $next($request);
    }
}